"""Mako template for Alembic autogenerated scripts.
"""
from alembic import op
import sqlalchemy as sa

% if context.get_x_argument(as_dictionary=True).get('rev_id'):
revision = '${rev_id}'
% else:
revision = '${up_revision}'
% endif
down_revision = ${down_revision if down_revision!="None" else None}
branch_labels = ${branch_labels if branch_labels!="None" else None}
depends_on = ${depends_on if depends_on!="None" else None}

def upgrade():
    pass

def downgrade():
    pass
